
# --- BCF Configuration ---
bcf.schema.version=3.0
foundation.version=1.1

# --- Spring Configuration ---
spring.server.port=8080
spring.application.name=BCFserver
spring.profiles.active=dev
spring.config.import=optional:file:.env[.properties]

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_SERVER_URL}/realms/${AUTH_REALM}
spring.security.oauth2.client.registration.bcf-server.client-id=${AUTH_CLIENT_ID}
spring.security.oauth2.client.registration.bcf-server.client-secret=${AUTH_CLIENT_SECRET}

# --- Auth ---
auth.provider=${AUTH_PROVIDER:keycloak}



