server:
  port: 8080

spring:
  application:
    name: BCFserver
  datasource:
    url: jdbc:postgresql://localhost:5432/bcfdb
    username: admin@bcf
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
