/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.openfabtwin.api;

import de.openfabtwin.dto.DocumentGET;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-05T09:23:37.160769500+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Documents", description = "the Documents API")
public interface DocumentsApi {

    String PATH_CREATE_DOCUMENT = "/bcf/{version}/projects/{project_id}/topics/{topic_id}/documents";
    /**
     * POST /bcf/{version}/projects/{project_id}/topics/{topic_id}/documents : Create Document
     * Upload a document (binary file) to a project. This operation is only possible when the server returns the createDocument flag in the Project authorization, see section 4.1.5 
     *
     * @param version  (required)
     * @param projectId  (required)
     * @param topicId  (required)
     * @param body  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "createDocument",
        summary = "Create Document",
        description = "Upload a document (binary file) to a project. This operation is only possible when the server returns the createDocument flag in the Project authorization, see section 4.1.5 ",
        tags = { "Documents" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DocumentGET.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = DocumentsApi.PATH_CREATE_DOCUMENT,
        produces = { "application/json" },
        consumes = { "application/octet-stream" }
    )
    ResponseEntity<DocumentGET> createDocument(
        @NotNull @Parameter(name = "version", description = "", required = true, in = ParameterIn.PATH) @PathVariable("version") String version,
        @NotNull @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") String projectId,
        @NotNull @Parameter(name = "topic_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("topic_id") String topicId,
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody org.springframework.core.io.Resource body
    );


    String PATH_GET_DOCUMENT = "/bcf/{version}/projects/{project_id}/topics/{topic_id}/documents";
    /**
     * GET /bcf/{version}/projects/{project_id}/topics/{topic_id}/documents : Get Documents
     * Retrieve a collection of all documents uploaded to a project. 
     *
     * @param version  (required)
     * @param projectId  (required)
     * @param topicId  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getDocument",
        summary = "Get Documents",
        description = "Retrieve a collection of all documents uploaded to a project. ",
        tags = { "Documents" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = DocumentGET.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = DocumentsApi.PATH_GET_DOCUMENT,
        produces = { "application/json" }
    )
    ResponseEntity<List<DocumentGET>> getDocument(
        @NotNull @Parameter(name = "version", description = "", required = true, in = ParameterIn.PATH) @PathVariable("version") String version,
        @NotNull @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") String projectId,
        @NotNull @Parameter(name = "topic_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("topic_id") String topicId
    );


    String PATH_GET_DOCUMENT_BY_ID = "/bcf/{version}/projects/{project_id}/documents/{document_id}";
    /**
     * GET /bcf/{version}/projects/{project_id}/documents/{document_id} : Get Document
     * Retrieves a document as binary file. 
     *
     * @param version  (required)
     * @param projectId  (required)
     * @param documentId  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getDocumentById",
        summary = "Get Document",
        description = "Retrieves a document as binary file. ",
        tags = { "Documents" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = org.springframework.core.io.Resource.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = DocumentsApi.PATH_GET_DOCUMENT_BY_ID,
        produces = { "application/octet-stream" }
    )
    ResponseEntity<org.springframework.core.io.Resource> getDocumentById(
        @NotNull @Parameter(name = "version", description = "", required = true, in = ParameterIn.PATH) @PathVariable("version") String version,
        @NotNull @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") String projectId,
        @NotNull @Parameter(name = "document_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("document_id") String documentId
    );

}
