/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.openfabtwin.api;

import de.openfabtwin.dto.CommentEventGET;
import org.springframework.lang.Nullable;
import de.openfabtwin.dto.TopicEventGET;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-03T12:04:39.178099100+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Events", description = "the Events API")
public interface EventsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_GET_COMMENT_EVENT = "/bcf/{version}/projects/{project_id}/topics/{topic_id}/comments/{comment_id}/events";
    /**
     * GET /bcf/{version}/projects/{project_id}/topics/{topic_id}/comments/{comment_id}/events : Get Comment Event
     * Retrieve a collection of comment events related to a comment (default sort order is date). 
     *
     * @param version  (required)
     * @param projectId  (required)
     * @param topicId  (required)
     * @param commentId  (required)
     * @param $top  (optional)
     * @param $skip  (optional)
     * @param $filter Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)  |parameter|type|description| |---------|----|-----------| |author|string|userId of the author (value from extensions)| |date|datetime|date of the event| |type|string|type of the event (value from Comment event types, table above)|  (optional)
     * @param $orderby Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)  |parameter|description| |---------|-----------| |date|date of the event|  (optional)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getCommentEvent",
        summary = "Get Comment Event",
        description = "Retrieve a collection of comment events related to a comment (default sort order is date). ",
        tags = { "Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = CommentEventGET.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = EventsApi.PATH_GET_COMMENT_EVENT,
        produces = { "application/json" }
    )
    default ResponseEntity<List<CommentEventGET>> getCommentEvent(
        @NotNull @Parameter(name = "version", description = "", required = true, in = ParameterIn.PATH) @PathVariable("version") String version,
        @NotNull @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") String projectId,
        @NotNull @Parameter(name = "topic_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("topic_id") String topicId,
        @NotNull @Parameter(name = "comment_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("comment_id") String commentId,
        @Parameter(name = "$top", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "$top", required = false) @Nullable String $top,
        @Parameter(name = "$skip", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "$skip", required = false) @Nullable String $skip,
        @Parameter(name = "$filter", description = "Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)  |parameter|type|description| |---------|----|-----------| |author|string|userId of the author (value from extensions)| |date|datetime|date of the event| |type|string|type of the event (value from Comment event types, table above)| ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "$filter", required = false) @Nullable String $filter,
        @Parameter(name = "$orderby", description = "Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)  |parameter|description| |---------|-----------| |date|date of the event| ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "$orderby", required = false) @Nullable String $orderby
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"date\" : \"date\", \"author\" : \"author\", \"topic_guid\" : \"topic_guid\", \"actions\" : [ { \"type\" : \"type\", \"value\" : \"value\" }, { \"type\" : \"type\", \"value\" : \"value\" } ], \"comment_guid\" : \"comment_guid\" }, { \"date\" : \"date\", \"author\" : \"author\", \"topic_guid\" : \"topic_guid\", \"actions\" : [ { \"type\" : \"type\", \"value\" : \"value\" }, { \"type\" : \"type\", \"value\" : \"value\" } ], \"comment_guid\" : \"comment_guid\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_COMMENT_EVENTS = "/bcf/{version}/projects/{project_id}/topics/comments/events";
    /**
     * GET /bcf/{version}/projects/{project_id}/topics/comments/events : Get Comments Events
     * Retrieve a collection of comment events related to a project (default sort order is date). 
     *
     * @param version  (required)
     * @param projectId  (required)
     * @param $top  (optional)
     * @param $skip  (optional)
     * @param $filter Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)  |parameter|type|description| |---------|----|-----------| |comment_guid|string|guid of the comment | |topic_guid|string|guid of the topic | |author|string|userId of the author (value from extensions)| |date|datetime|date of the event| |type|string|type of the event (value from Comment event types, table above)|  (optional)
     * @param $orderby Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)  |parameter|description| |---------|-----------| |date|date of the event|  (optional)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getCommentEvents",
        summary = "Get Comments Events",
        description = "Retrieve a collection of comment events related to a project (default sort order is date). ",
        tags = { "Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = CommentEventGET.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = EventsApi.PATH_GET_COMMENT_EVENTS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<CommentEventGET>> getCommentEvents(
        @NotNull @Parameter(name = "version", description = "", required = true, in = ParameterIn.PATH) @PathVariable("version") String version,
        @NotNull @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") String projectId,
        @Parameter(name = "$top", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "$top", required = false) @Nullable String $top,
        @Parameter(name = "$skip", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "$skip", required = false) @Nullable String $skip,
        @Parameter(name = "$filter", description = "Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)  |parameter|type|description| |---------|----|-----------| |comment_guid|string|guid of the comment | |topic_guid|string|guid of the topic | |author|string|userId of the author (value from extensions)| |date|datetime|date of the event| |type|string|type of the event (value from Comment event types, table above)| ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "$filter", required = false) @Nullable String $filter,
        @Parameter(name = "$orderby", description = "Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)  |parameter|description| |---------|-----------| |date|date of the event| ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "$orderby", required = false) @Nullable String $orderby
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"date\" : \"date\", \"author\" : \"author\", \"topic_guid\" : \"topic_guid\", \"actions\" : [ { \"type\" : \"type\", \"value\" : \"value\" }, { \"type\" : \"type\", \"value\" : \"value\" } ], \"comment_guid\" : \"comment_guid\" }, { \"date\" : \"date\", \"author\" : \"author\", \"topic_guid\" : \"topic_guid\", \"actions\" : [ { \"type\" : \"type\", \"value\" : \"value\" }, { \"type\" : \"type\", \"value\" : \"value\" } ], \"comment_guid\" : \"comment_guid\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_EVENTS = "/bcf/{version}/projects/{project_id}/topics/events";
    /**
     * GET /bcf/{version}/projects/{project_id}/topics/events : Get Topics Events
     * Retrieves a document as binary file. 
     *
     * @param version  (required)
     * @param projectId  (required)
     * @param $top  (optional)
     * @param $skip  (optional)
     * @param $filter Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)  |parameter|type|description| |---------|----|-----------| |topic_guid|string|guid of the topic | |author|string|userId of the author (value from extensions)| |type|string|type of the event (value from Topic event types, table above)| |date|datetime|date of the event|  (optional)
     * @param $orderby Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)  |parameter|description| |---------|-----------| |date|date of the event|  (optional)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getEvents",
        summary = "Get Topics Events",
        description = "Retrieves a document as binary file. ",
        tags = { "Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = TopicEventGET.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = EventsApi.PATH_GET_EVENTS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<TopicEventGET>> getEvents(
        @NotNull @Parameter(name = "version", description = "", required = true, in = ParameterIn.PATH) @PathVariable("version") String version,
        @NotNull @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") String projectId,
        @Parameter(name = "$top", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "$top", required = false) @Nullable String $top,
        @Parameter(name = "$skip", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "$skip", required = false) @Nullable String $skip,
        @Parameter(name = "$filter", description = "Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)  |parameter|type|description| |---------|----|-----------| |topic_guid|string|guid of the topic | |author|string|userId of the author (value from extensions)| |type|string|type of the event (value from Topic event types, table above)| |date|datetime|date of the event| ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "$filter", required = false) @Nullable String $filter,
        @Parameter(name = "$orderby", description = "Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)  |parameter|description| |---------|-----------| |date|date of the event| ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "$orderby", required = false) @Nullable String $orderby
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"date\" : \"date\", \"author\" : \"author\", \"topic_guid\" : \"topic_guid\", \"actions\" : [ { \"type\" : \"type\", \"value\" : \"value\" }, { \"type\" : \"type\", \"value\" : \"value\" } ] }, { \"date\" : \"date\", \"author\" : \"author\", \"topic_guid\" : \"topic_guid\", \"actions\" : [ { \"type\" : \"type\", \"value\" : \"value\" }, { \"type\" : \"type\", \"value\" : \"value\" } ] } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_TOPIC_EVENTS = "/bcf/{version}/projects/{project_id}/topics/{topic_id}/events";
    /**
     * GET /bcf/{version}/projects/{project_id}/topics/{topic_id}/events : Get Topic Events
     * Retrieve a collection of topic events related to a project (default sort order is date). 
     *
     * @param version  (required)
     * @param projectId  (required)
     * @param topicId  (required)
     * @param $top  (optional)
     * @param $skip  (optional)
     * @param $filter Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)  |parameter|type|description| |---------|----|-----------| |author|string|userId of the author (value from extensions)| |type|string|type of the event (value from Topic event types, table above)| |date|datetime|date of the event|  (optional)
     * @param $orderby Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)  |parameter|description| |---------|-----------| |date|date of the event|  (optional)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getTopicEvents",
        summary = "Get Topic Events",
        description = "Retrieve a collection of topic events related to a project (default sort order is date). ",
        tags = { "Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = TopicEventGET.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = EventsApi.PATH_GET_TOPIC_EVENTS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<TopicEventGET>> getTopicEvents(
        @NotNull @Parameter(name = "version", description = "", required = true, in = ParameterIn.PATH) @PathVariable("version") String version,
        @NotNull @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") String projectId,
        @NotNull @Parameter(name = "topic_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("topic_id") String topicId,
        @Parameter(name = "$top", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "$top", required = false) @Nullable String $top,
        @Parameter(name = "$skip", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "$skip", required = false) @Nullable String $skip,
        @Parameter(name = "$filter", description = "Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)  |parameter|type|description| |---------|----|-----------| |author|string|userId of the author (value from extensions)| |type|string|type of the event (value from Topic event types, table above)| |date|datetime|date of the event| ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "$filter", required = false) @Nullable String $filter,
        @Parameter(name = "$orderby", description = "Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)  |parameter|description| |---------|-----------| |date|date of the event| ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "$orderby", required = false) @Nullable String $orderby
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"date\" : \"date\", \"author\" : \"author\", \"topic_guid\" : \"topic_guid\", \"actions\" : [ { \"type\" : \"type\", \"value\" : \"value\" }, { \"type\" : \"type\", \"value\" : \"value\" } ] }, { \"date\" : \"date\", \"author\" : \"author\", \"topic_guid\" : \"topic_guid\", \"actions\" : [ { \"type\" : \"type\", \"value\" : \"value\" }, { \"type\" : \"type\", \"value\" : \"value\" } ] } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
