/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.openfabtwin.api;

import de.openfabtwin.dto.FileGET;
import de.openfabtwin.dto.FilePUT;
import de.openfabtwin.dto.ProjectFileInformation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-05T09:23:37.160769500+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Files", description = "the Files API")
public interface FilesApi {

    String PATH_GET_FILES = "/bcf/{version}/projects/{project_id}/topics/{topic_id}/files";
    /**
     * GET /bcf/{version}/projects/{project_id}/topics/{topic_id}/files : Get Files
     * Retrieve a collection of file references as topic header.  Implementer Note: The reference property can either be an Uri or a server specific id. Uris are given as absolute paths to the model files while ids reference a custom id of the model file and require custom logic per server to retrieve it. This allows referencing of files on the server but requires clients to know how to retrieve files in a specific implementation. 
     *
     * @param version  (required)
     * @param projectId  (required)
     * @param topicId  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getFiles",
        summary = "Get Files",
        description = "Retrieve a collection of file references as topic header.  Implementer Note: The reference property can either be an Uri or a server specific id. Uris are given as absolute paths to the model files while ids reference a custom id of the model file and require custom logic per server to retrieve it. This allows referencing of files on the server but requires clients to know how to retrieve files in a specific implementation. ",
        tags = { "Files" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = FileGET.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = FilesApi.PATH_GET_FILES,
        produces = { "application/json" }
    )
    ResponseEntity<List<FileGET>> getFiles(
        @NotNull @Parameter(name = "version", description = "", required = true, in = ParameterIn.PATH) @PathVariable("version") String version,
        @NotNull @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") String projectId,
        @NotNull @Parameter(name = "topic_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("topic_id") String topicId
    );


    String PATH_GET_PROJECT_FILES_INFORMATION = "/bcf/{version}/projects/{project_id}/files_information";
    /**
     * GET /bcf/{version}/projects/{project_id}/files_information : Get Files Information
     * Retrieve a collection of project_file_informations to support allowing users to choose which Files (models) to reference in the header of topics created on the server. 
     *
     * @param version  (required)
     * @param projectId  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getProjectFilesInformation",
        summary = "Get Files Information",
        description = "Retrieve a collection of project_file_informations to support allowing users to choose which Files (models) to reference in the header of topics created on the server. ",
        tags = { "Files" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ProjectFileInformation.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = FilesApi.PATH_GET_PROJECT_FILES_INFORMATION,
        produces = { "application/json" }
    )
    ResponseEntity<List<ProjectFileInformation>> getProjectFilesInformation(
        @NotNull @Parameter(name = "version", description = "", required = true, in = ParameterIn.PATH) @PathVariable("version") String version,
        @NotNull @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") String projectId
    );


    String PATH_UPDATE_TOPIC_FILE = "/bcf/{version}/projects/{project_id}/topics/{topic_id}/files";
    /**
     * PUT /bcf/{version}/projects/{project_id}/topics/{topic_id}/files : Update File
     * Update a collection of file references on the topic header. This operation is only possible when the server returns the updateFiles flag in the Topic authorization, see section 3.2.8 
     *
     * @param version  (required)
     * @param projectId  (required)
     * @param topicId  (required)
     * @param filePUT  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "updateTopicFile",
        summary = "Update File",
        description = "Update a collection of file references on the topic header. This operation is only possible when the server returns the updateFiles flag in the Topic authorization, see section 3.2.8 ",
        tags = { "Files" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = FileGET.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = FilesApi.PATH_UPDATE_TOPIC_FILE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<List<FileGET>> updateTopicFile(
        @NotNull @Parameter(name = "version", description = "", required = true, in = ParameterIn.PATH) @PathVariable("version") String version,
        @NotNull @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") String projectId,
        @NotNull @Parameter(name = "topic_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("topic_id") String topicId,
        @Parameter(name = "FilePUT", description = "", required = true) @Valid @RequestBody List<@Valid FilePUT> filePUT
    );

}
