/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.openfabtwin.api;

import de.openfabtwin.dto.ExtensionsGET;
import de.openfabtwin.dto.ProjectGET;
import de.openfabtwin.dto.ProjectPUT;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-05T09:23:37.160769500+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Project", description = "the Project API")
public interface ProjectApi {

    String PATH_GET_ALL_PROJECTS = "/bcf/{version}/projects";
    /**
     * GET /bcf/{version}/projects : Get Projects
     * Retrieve a collection of projects where the currently logged on user has access to.
     *
     * @param version  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getAllProjects",
        summary = "Get Projects",
        description = "Retrieve a collection of projects where the currently logged on user has access to.",
        tags = { "Project" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ProjectGET.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProjectApi.PATH_GET_ALL_PROJECTS,
        produces = { "application/json" }
    )
    ResponseEntity<List<ProjectGET>> getAllProjects(
        @NotNull @Parameter(name = "version", description = "", required = true, in = ParameterIn.PATH) @PathVariable("version") String version
    );


    String PATH_GET_PROJECT_BY_ID = "/bcf/{version}/projects/{project_id}";
    /**
     * GET /bcf/{version}/projects/{project_id} : Get Project
     * Retrieve a specific project.
     *
     * @param version  (required)
     * @param projectId  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getProjectById",
        summary = "Get Project",
        description = "Retrieve a specific project.",
        tags = { "Project" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProjectGET.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProjectApi.PATH_GET_PROJECT_BY_ID,
        produces = { "application/json" }
    )
    ResponseEntity<ProjectGET> getProjectById(
        @NotNull @Parameter(name = "version", description = "", required = true, in = ParameterIn.PATH) @PathVariable("version") String version,
        @NotNull @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") String projectId
    );


    String PATH_GET_PROJECT_EXTENSION = "/bcf/{version}/projects/{project_id}/extensions";
    /**
     * GET /bcf/{version}/projects/{project_id}/extensions : Get Project Extensions
     * Retrieve a specific projects extensions. Project extensions are used to define possible values that can be used in topics and comments, for example topic labels and priorities. They may change during the course of a project. The most recent extensions state which values are valid at a given moment for newly created topics and comments. 
     *
     * @param version  (required)
     * @param projectId  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getProjectExtension",
        summary = "Get Project Extensions",
        description = "Retrieve a specific projects extensions. Project extensions are used to define possible values that can be used in topics and comments, for example topic labels and priorities. They may change during the course of a project. The most recent extensions state which values are valid at a given moment for newly created topics and comments. ",
        tags = { "Project" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ExtensionsGET.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProjectApi.PATH_GET_PROJECT_EXTENSION,
        produces = { "application/json" }
    )
    ResponseEntity<ExtensionsGET> getProjectExtension(
        @NotNull @Parameter(name = "version", description = "", required = true, in = ParameterIn.PATH) @PathVariable("version") String version,
        @NotNull @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") String projectId
    );


    String PATH_UPDATE_PROJECT_BY_ID = "/bcf/{version}/projects/{project_id}";
    /**
     * PUT /bcf/{version}/projects/{project_id} : Update Project
     * Modify a specific project. This operation is only possible when the server returns the update flag in the Project authorization, see section 3.1.5
     *
     * @param version  (required)
     * @param projectId  (required)
     * @param projectPUT  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "updateProjectById",
        summary = "Update Project",
        description = "Modify a specific project. This operation is only possible when the server returns the update flag in the Project authorization, see section 3.1.5",
        tags = { "Project" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProjectGET.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = ProjectApi.PATH_UPDATE_PROJECT_BY_ID,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<ProjectGET> updateProjectById(
        @NotNull @Parameter(name = "version", description = "", required = true, in = ParameterIn.PATH) @PathVariable("version") String version,
        @NotNull @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") String projectId,
        @Parameter(name = "ProjectPUT", description = "", required = true) @Valid @RequestBody ProjectPUT projectPUT
    );

}
